# Generated by Django 6.1.1 on 2026-09-09 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Ayurvedic product', max_length=150)),
                ('category', models.CharField(choices=[('hair_care', 'Hair Care'), ('face_care', 'Face & Skincare'), ('body_care', 'Body & Bath Care'), ('wellness', 'Herbal Wellness')], default='hair_care', help_text='Product category', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of ingredients, benefits, and usage')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR (₹)', max_digits=8)),
                ('image', models.ImageField(help_text='Upload a clear product photograph', upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide product from site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('message', models.TextField(blank=True, verbose_name='Message / Query')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Status Processed')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='backend.product', verbose_name='Requested Product')),
            ],
            options={
                'verbose_name': 'Customer Enquiry',
                'verbose_name_plural': 'Customer Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
