# Generated by Django 6.1.1 on 2026-09-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('resolved', 'Resolved')], default='new', help_text='Track enquiry progress as an informal order', max_length=20, verbose_name='Enquiry Status'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=25, help_text='Available inventory count in units'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hair_care', 'Hair Care'), ('face_care', 'Face & Skincare'), ('body_care', 'Body & Bath'), ('wellness', 'Wellness / General')], default='hair_care', help_text='Product category', max_length=50),
        ),
    ]
